env:
  node: true
  commonjs: true
  es6: true

extends:
  - airbnb-typescript/base
  - plugin:import/typescript

parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  sourceType: module

plugins:
  - '@typescript-eslint/eslint-plugin'
  - import
  - prettier

rules:
  '@typescript-eslint/indent': 'off' # We use prettier for indenting
  'import/prefer-default-export': 'off'
  'newline-per-chained-call': 'off'
  'max-len':
    - error
    - code: 120
      ignorePattern: import |export |`.*`|'.*'|// .*|\* .*

overrides:
  - files: ["*spec.ts"]
    rules:
      'max-classes-per-file': "off"
