language: node_js
node_js:
  - node

script:
  - npm run build
  - npm run lint
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

deploy:
  provider: npm
  email: me@joell.dev
  api_key:
    secure: uzEXFsW1tORNjBHtBrXrwK3PJR9i8agRekdAXxmT5qZgNaiGIbdelz1w5cdhZZa/FQPnw7UZDucl7KLQfKhYZCO1jtJdmUCtsykuM2o5bxWLlQs+Zve+RyKoVHmRVaTgOiCY/WkDw2eITNPWoi3PhISkvkWGYjsX4dLepzEkFWFUKNeLJ+gvWADokQcfx9HTb13FpYMFpxXcWC96yckQI9V/NDmIa+eFVNwaF5+BEckVZ2l1FjEV8VwZkVtlaBZYqlIN7GEFWA5eWCw8Xpxy4IyvqkkPFUbo9+UCLBew0p//661jVBwf+IxC46v6nGqijHvuudyUIkwmW4QPRZdTFNp0jUvTI51jmmrjJntbRHMw3TtxlGGcYYAGEKwYufU+sv2oDm6fuxES8lQPcM1mjWSCCkJU57awStIf6PzsZXjBBME4AL3OmHj25PKfgNs++jkfdKslP/3MqsyAdDo+47xA1Rycbn479IVu1iIhIxonRHa4ClxgZqn+RYHmOVohIUR3XPMX5FBwhSsc8Qhzq9Flk8uOdC02zcD2yH4rdsYNXmljeQW9rXpEQVQ3zDUsUuUjK6ZQHDKyki3Rd09M0qm6el3RI1qN9ESvS3dbY/CthO7ZVhSQY2yM+kVx6XNbynCGS46lSTc4DK/w2hfzd1n9T3xRdtH0T2bJ00oXaKk=
  on:
    tags: true
    repo: gynzy/mapper
  skip_cleanup: 'true'
