language: node_js
node_js:
  - node

script:
  - npm run lint
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage


deploy:
  provider: npm
  email: "me@joell.app"
  api_key:
    secure: "LS9Miq5ttrIGIdbhGjpXSfnH6aa4Ff6/Xe0v8UWEdGAtqvjuUmhER1K6+q0xqZfYNL85JsG/1wUnhgG63QXmpWkOsFH2hMa/hPUlvD5A90WX1D2KKsP9h/gBT6cEmnRCAmusy8XcRkLkS6ODhPvHmCgqtnXmgrcI609SXEMlfkZnNtrVIotCRB2+99KfViBAPq1iFqxZJ/s0kZLFv3k0tn1sswEZGx6zbI5zyiq92nRzoWrTiOTW0JBNVdEb2ObL4Fd0UdP9koeI27jSVASDb/1g7pXYomBw0nDzY5sl0X+4WteTz9teADjRH2jnhdtw6KTfp2PomoDKZJhve3rKHE0B0VWZzqH3sYT9SCRyyaZiO+S+5OvyBbqLShiPFUkTqJROaZZz8srvPak+uE+lNLytYzEa8OoXkXvFAWFmnjI10NUgn0u8WZzSgNsx4+WbDdljfDCL9bSP85vm/DNAZdzE5WNbyEEt1JmVcLjgexl9Eu+JQ2GR9zTZXq09mVXCh9WY7jnshYweO80sYurlouixkndwHkb20Geq8YTxzACLpJmTt8lLXpdBmtUcGPzWUqC2BdeXM8OZ5uSzhn9J8FJNLH8/J+K5/UvtDFbpZNAiNO9DwxyjucgvBqstcldIHcuLsywcCaEaYiC6K17btEUynujgFRAJsljA4dHDXDs="
  on:
    tags: true
